### ISSUE TITLE
UI: Weather Component (Student 3/4)

### ISSUE THREAD

**Issue by madhuriprao** [liamanders/local-travel-weather#11]
create the Weather component and display the local weather for the user's
location, including temperature, weather conditions and an icon for the weather (e.g., sun, cloud). 

User story:
Using the geographic coordinates from the address, the app will fetch
local weather data from the OpenWeather API.
It will show the current temperature, weather conditions (like sunny,
rainy, or cloudy), and a weather icon.

**Comment by surba778** [comment]
Done.
